### ISSUE TITLE
Retire dirac-institute/axs-examples

### ISSUE THREAD

**Issue by mjuric** [astronomy-commons/tutorials#6]
@stevenstetzler -- I'm consolidating/reorganizing various repos we have. I've merged the contents of `axs-examples` into this repo; I think it will be easier to manage all demos from one place. Can you update the genesis hub to pull from this repository? Also, archive `axs-examples` git repo when done.

Also tagging @zgolkhou, to keep him up to date with the move.

**Comment by stevenstetzler** [comment]
I've updated the hub to pull from here and archived the `axs-examples` repo.
